# ==========================================
# Global Configuration
# ==========================================

global:

  scrape_interval: 15s

  evaluation_interval: 15s


  external_labels:
    replica: prometheus-a


# ==========================================
# Scrape Configurations
# ==========================================

scrape_configs:

# Prometheus itself

- job_name: "prometheus-a"

  static_configs:

  - targets:

    - localhost:9090